// Playlist
export const ADD_SONG_ERROR = 'ADD_SONG_ERROR';
export const PLAY_NEXT = 'PLAY_NEXT';
export const PLAYLIST_FETCHING = 'PLAYLIST_FETCHING';
export const PLAYLIST_FETCH_SUCCESS = 'PLAYLIST_FETCH_SUCCESS';
export const PLAYLIST_FETCH_ERROR = 'PLAYLIST_FETCH_ERROR';

// Playlists
export const UPDATE_PLAYLISTS = 'UPDATE_PLAYLISTS';
